# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iBeacon' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iBeacon

  # 통신
  pod 'Alamofire', '4.9.0'

  # 이미지 비동기화
  pod 'Nuke'
  
end
